#!/bin/bash

style=$(cat $HOME/.config/dunst/sid)

if [[ "$style" == "Light" ]]; then
	amixer -Mq set Master,0 5%- unmute && dunstify "Volume Down: $(amixer get Master | grep -oP '[0-9]{1,3}%')"
else
	amixer -Mq set Master,0 5%- unmute && dunstify "Volume Down: $(amixer get Master | grep -oP '[0-9]{1,3}%')"
fi
